import { Category, Product, PromoCode, AnnouncementBanner, Order } from "@/types";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Woolen Mat Rangolis",
    slug: "woolen-rangolis",
    description: "Washable, durable & reusable handmade woolen rangolis featuring sacred Indian motifs.",
    iconName: "Sparkles",
    image: "https://images.unsplash.com/photo-1605651202774-7d573fd3f12d?auto=format&fit=crop&q=80&w=800",
    tagline: "Reinvent your entrance with everlasting woolen art",
    itemCount: 8,
  },
  {
    id: "cat-2",
    name: "Entrance & Torans",
    slug: "entrance-torans",
    description: "Auspicious door hangings, Shubh-Labh sets, and handcrafted entryway borders.",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&q=80&w=800",
    tagline: "Welcome blessings right at your doorstep",
    itemCount: 5,
  },
  {
    id: "cat-3",
    name: "Pooja & Thali Mats",
    slug: "pooja-thali-mats",
    description: "Washable protective mats for brass thalis, diyas, and temple asanas.",
    iconName: "Flame",
    image: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=800",
    tagline: "Pure, sacred elegance for daily poojas and rituals",
    itemCount: 6,
  },
  {
    id: "cat-4",
    name: "Home & Living Mats",
    slug: "home-decor-mats",
    description: "Artisanal woolen centrepieces, dining table runners, and decorative floor mats.",
    iconName: "Palette",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800",
    tagline: "Warm, cozy handcrafted charm for every room",
    itemCount: 5,
  },
  {
    id: "cat-5",
    name: "Festive & Custom Hampers",
    slug: "festive-hampers",
    description: "Curated gift boxes with personalized nameplates and handcrafted sets.",
    iconName: "Gift",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=800",
    tagline: "Thoughtful handmade gifting for weddings & housewarmings",
    itemCount: 4,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Auspicious Kalash & Shubh-Labh Woolen Rangoli Mat",
    slug: "kalash-shubh-labh-woolen-rangoli",
    subtitle: "Sacred Kalash with mango leaves & circular flower petal borders",
    description: "Expertly handcrafted with soft, premium quality acrylic yarn on an anti-slip backing. Featuring a sacred Kalash adorned with coconuts and mango leaves, flanked by delicate circular flower motifs.",
    detailedDescription: "Designed specifically for modern Indian homes who cherish traditions without the mess of powder colors. This reusable woolen rangoli mat can be placed at the entrance, in your pooja room, or as a dining centrepiece. It is 100% washable, durable, and folds effortlessly for easy storage after every celebration.",
    category: "woolen-rangolis",
    price: 899,
    compareAtPrice: 1299,
    inStock: true,
    stockCount: 12,
    isBestseller: true,
    isNewArrival: false,
    isCustomizable: true,
    featuredMotif: "Kalash",
    motifs: ["Kalash", "Shubh-Labh", "Circular Flowers"],
    images: [
      "https://images.unsplash.com/photo-1605651202774-7d573fd3f12d?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=900",
    ],
    features: [
      "100% Handcrafted by Aarya with premium 4-ply yarn",
      "Washable, fold-friendly & reusable for 5+ years",
      "Anti-slip felt backing prevents slipping on tiles & marble",
      "Custom color combinations & diameter sizes available upon request",
    ],
    specifications: {
      material: "Premium Acrylic Wool & Velvet Yarn",
      washCare: "Gentle hand wash in cold water with mild detergent; dry flat",
      craftTime: "2 to 3 days dedicated hand-knitting",
      durability: "High tensile woolen weave, colorfast yarn",
      baseMaterial: "Anti-slip Heavy Felt & Interlocking Canvas",
      reusable: true,
    },
    sizes: [
      { id: "s-12", label: "Small (12\" Diameter)", dimensions: "12 x 12 inches (30 cm)", priceMultiplier: 0.8 },
      { id: "s-18", label: "Medium (18\" Diameter)", dimensions: "18 x 18 inches (45 cm)", priceMultiplier: 1.0, isPopular: true },
      { id: "s-24", label: "Grand (24\" Centrepiece)", dimensions: "24 x 24 inches (60 cm)", priceMultiplier: 1.55 },
      { id: "s-30", label: "Royal (30\" Grand Entrance)", dimensions: "30 x 30 inches (75 cm)", priceMultiplier: 2.1 },
    ],
    colorThemes: [
      { id: "c-haldi", name: "Haldi Yellow & Rani Pink", colors: ["#FBBF24", "#E11D48"], previewTag: "Auspicious" },
      { id: "c-maroon", name: "Royal Maroon & Golden Ochre", colors: ["#881337", "#D97706"], previewTag: "Festive" },
      { id: "c-peacock", name: "Peacock Blue & Emerald Green", colors: ["#0284C7", "#059669"], previewTag: "Royal" },
      { id: "c-pastel", name: "Pastel Peach & Mint Green", colors: ["#FDBA74", "#6EE7B7"], previewTag: "Contemporary" },
    ],
    rating: 4.9,
    reviewsCount: 48,
  },
  {
    id: "prod-2",
    title: "Mor Pankh (Peacock Feather) Handcrafted Woolen Rangoli",
    slug: "mor-pankh-peacock-feather-rangoli",
    subtitle: "Vibrant peacock shades with royal gold border detailing",
    description: "Inspired by the divine beauty of Lord Krishna's peacock feather. Hand-stitched with deep royal blue, emerald green, and shimmering gold accents.",
    detailedDescription: "A showstopper piece designed for living room entrances, Janmashtami celebrations, Diwali poojas, and everyday cultural elegance. Built with dense woolen loops that give a lush 3D texture.",
    category: "woolen-rangolis",
    price: 949,
    compareAtPrice: 1399,
    inStock: true,
    stockCount: 8,
    isBestseller: true,
    isNewArrival: true,
    isCustomizable: true,
    featuredMotif: "Mor Pankh",
    motifs: ["Mor Pankh", "Lotus", "Circular Flowers"],
    images: [
      "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1605651202774-7d573fd3f12d?auto=format&fit=crop&q=80&w=900",
    ],
    features: [
      "Rich 3D textured peacock feather weave",
      "Vibrant fade-proof colors",
      "Easy to dust off and hand-washable",
      "Perfect for pooja platforms and main entrance foyers",
    ],
    specifications: {
      material: "High-grade Soft Acrylic Wool",
      washCare: "Mild soak, do not wring harshly, dry in shade",
      craftTime: "3 days per unit",
      durability: "Long-lasting dense stitch",
      baseMaterial: "Reinforced Anti-skid backing",
      reusable: true,
    },
    sizes: [
      { id: "s-14", label: "Compact (14\" Diameter)", dimensions: "14 x 14 inches", priceMultiplier: 0.85 },
      { id: "s-18", label: "Standard (18\" Diameter)", dimensions: "18 x 18 inches", priceMultiplier: 1.0, isPopular: true },
      { id: "s-24", label: "Grand (24\" Diameter)", dimensions: "24 x 24 inches", priceMultiplier: 1.55 },
    ],
    colorThemes: [
      { id: "c-peacock-classic", name: "Classic Royal Blue & Emerald", colors: ["#1E40AF", "#047857"], previewTag: "Signature" },
      { id: "c-peacock-gold", name: "Peacock Blue & Mustard Gold", colors: ["#1E3A8A", "#D97706"] },
    ],
    rating: 5.0,
    reviewsCount: 36,
  },
  {
    id: "prod-3",
    title: "Laxmi Charan & Lotus (Kamal) Auspicious Entrance Mat",
    slug: "laxmi-charan-lotus-auspicious-mat",
    subtitle: "Divine lotus petal bloom with sacred Laxmi footprints",
    description: "Welcome goddess Laxmi into your home every single day. Features divine golden footprints embedded within a layered blooming lotus flower.",
    detailedDescription: "Hand-crafted with auspicious red and golden wool. Replaces temporary powder footprints with an enduring, neat, and reusable sacred decor piece for Diwali, Varalakshmi Pooja, and housewarmings.",
    category: "woolen-rangolis",
    price: 799,
    compareAtPrice: 1149,
    inStock: true,
    stockCount: 15,
    isBestseller: true,
    isNewArrival: false,
    isCustomizable: true,
    featuredMotif: "Laxmi Charan",
    motifs: ["Laxmi Charan", "Lotus", "Swastik"],
    images: [
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1605651202774-7d573fd3f12d?auto=format&fit=crop&q=80&w=900",
    ],
    features: [
      "Sacred symbolic footprint motif at the nucleus",
      "Multi-tier lotus petal design with golden trims",
      "Durable, soft to walk on, stain-resistant",
    ],
    specifications: {
      material: "Velvet Soft Wool & Golden Zari Thread",
      washCare: "Quick gentle hand wash; rinse in cold water",
      craftTime: "2 days",
      durability: "Fade-resistant yarn",
      baseMaterial: "Non-slip grip mat",
      reusable: true,
    },
    sizes: [
      { id: "s-12", label: "Pooja Size (12\" Diameter)", dimensions: "12 x 12 inches", priceMultiplier: 0.8 },
      { id: "s-16", label: "Entrance Standard (16\" Diameter)", dimensions: "16 x 16 inches", priceMultiplier: 1.0, isPopular: true },
      { id: "s-20", label: "Grand Entrance (20\" Diameter)", dimensions: "20 x 20 inches", priceMultiplier: 1.35 },
    ],
    colorThemes: [
      { id: "c-lotus-pink", name: "Rani Pink & Sunshine Yellow", colors: ["#BE185D", "#FBBF24"], previewTag: "Most Loved" },
      { id: "c-lotus-red", name: "Kumkum Red & Sandalwood Cream", colors: ["#DC2626", "#FEF3C7"] },
      { id: "c-lotus-orange", name: "Marigold Orange & Deep Red", colors: ["#EA580C", "#991B1B"] },
    ],
    rating: 4.9,
    reviewsCount: 52,
  },
  {
    id: "prod-4",
    title: "Lord Ganesha & Swastik Divine Centrepiece Mat",
    slug: "lord-ganesha-swastik-centrepiece-mat",
    subtitle: "Vighnaharta Ganesha outline surrounded by traditional floral patterns",
    description: "An auspicious symbol of prosperity and new beginnings. Hand-embroidered woolen knots depict Lord Ganesha with a gentle Swastik motif border.",
    detailedDescription: "Ideal for Ganesh Chaturthi, Griha Pravesh, Diwali, or as a permanent spiritual centrepiece on temple tables and living room low tables.",
    category: "woolen-rangolis",
    price: 999,
    compareAtPrice: 1499,
    inStock: true,
    stockCount: 7,
    isBestseller: false,
    isNewArrival: true,
    isCustomizable: true,
    featuredMotif: "Ganesha",
    motifs: ["Ganesha", "Swastik", "Om", "Diya"],
    images: [
      "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1605651202774-7d573fd3f12d?auto=format&fit=crop&q=80&w=900",
    ],
    features: [
      "Detailed Lord Ganesha silhouette woven with precision",
      "Heavy density yarn providing a plush feel",
      "Can also be framed as sacred wall tapestry",
    ],
    specifications: {
      material: "Premium Indian Acrylic Wool",
      washCare: "Hand wash with shampoo or mild detergent",
      craftTime: "3 to 4 days",
      durability: "Superior lock-stitch yarn technique",
      baseMaterial: "Anti-slip thermal felt",
      reusable: true,
    },
    sizes: [
      { id: "s-16", label: "Standard (16\" Diameter)", dimensions: "16 x 16 inches", priceMultiplier: 1.0, isPopular: true },
      { id: "s-22", label: "Grand (22\" Diameter)", dimensions: "22 x 22 inches", priceMultiplier: 1.45 },
      { id: "s-28", label: "Grand Foyer (28\" Diameter)", dimensions: "28 x 28 inches", priceMultiplier: 1.95 },
    ],
    colorThemes: [
      { id: "c-ganesha-red", name: "Sindoor Red & Haldi Gold", colors: ["#B91C1C", "#F59E0B"], previewTag: "Auspicious" },
      { id: "c-ganesha-orange", name: "Kesari Orange & Rani Pink", colors: ["#C2410C", "#DB2777"] },
      { id: "c-ganesha-maroon", name: "Royal Maroon & Cream", colors: ["#7F1D1D", "#FFFBEB"] },
    ],
    rating: 4.8,
    reviewsCount: 29,
  },
  {
    id: "prod-5",
    title: "Rose Bloom Handcrafted Woolen Decor Mat",
    slug: "rose-bloom-handcrafted-woolen-decor-mat",
    subtitle: "Evergreen multi-tier floral design for tables & bedside accents",
    description: "An elegant circular rose pattern crafted with soft pastel yarns. Adds warmth, color, and cozy handmade artistry to modern home interiors.",
    detailedDescription: "Created for everyday home decor lovers. Looks stunning under glass table vases, table lamps, bedside consoles, or as a cozy floor accent.",
    category: "home-decor-mats",
    price: 699,
    compareAtPrice: 999,
    inStock: true,
    stockCount: 14,
    isBestseller: false,
    isNewArrival: true,
    isCustomizable: true,
    featuredMotif: "Rose",
    motifs: ["Rose", "Circular Flowers"],
    images: [
      "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=900",
    ],
    features: [
      "Modern botanical aesthetic with Indian handmade touch",
      "Super soft wool that feels wonderful to the touch",
      "Machine gentle cycle or hand washable",
    ],
    specifications: {
      material: "Super-soft Micro-acrylic Yarn",
      washCare: "Gentle hand wash; flat dry",
      craftTime: "2 days",
      durability: "Reinforced edges",
      baseMaterial: "Soft felt base",
      reusable: true,
    },
    sizes: [
      { id: "s-12", label: "Coaster Size (12\" Diameter)", dimensions: "12 x 12 inches", priceMultiplier: 0.75 },
      { id: "s-16", label: "Table Accent (16\" Diameter)", dimensions: "16 x 16 inches", priceMultiplier: 1.0, isPopular: true },
      { id: "s-20", label: "Large Table Mat (20\" Diameter)", dimensions: "20 x 20 inches", priceMultiplier: 1.35 },
    ],
    colorThemes: [
      { id: "c-rose-blush", name: "Blush Rose Pink & Off-White", colors: ["#F472B6", "#FAFAF9"], previewTag: "Top Choice" },
      { id: "c-rose-coral", name: "Coral Peach & Sage Green", colors: ["#FB923C", "#86EFAC"] },
      { id: "c-rose-crimson", name: "Deep Crimson & Champagne Gold", colors: ["#991B1B", "#FDE68A"] },
    ],
    rating: 4.9,
    reviewsCount: 22,
  },
  {
    id: "prod-6",
    title: "Shubh-Labh Corner & Entrance Border Accents (Set of 4)",
    slug: "shubh-labh-corner-entrance-border-set",
    subtitle: "Decorative corner motifs for doorway frames and floor rangoli edges",
    description: "Accentuate your main door, rangoli borders, or pooja altar with these 4-piece handmade woolen corner pieces inscribed with Shubh and Labh.",
    detailedDescription: "Designed with corner L-shapes and circular florals that frame any existing mat or doorway seamlessly. Comes with optional nano-grip adhesive dots.",
    category: "entrance-torans",
    price: 649,
    compareAtPrice: 899,
    inStock: true,
    stockCount: 18,
    isBestseller: true,
    isNewArrival: false,
    isCustomizable: true,
    featuredMotif: "Shubh-Labh",
    motifs: ["Shubh-Labh", "Swastik", "Circular Flowers"],
    images: [
      "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1605651202774-7d573fd3f12d?auto=format&fit=crop&q=80&w=900",
    ],
    features: [
      "Complete set of 4 matching corners for doors & mats",
      "Includes non-marking removable adhesive backing",
      "Re-usable across multiple festivals and occasions",
    ],
    specifications: {
      material: "Hand-spun Acrylic Thread & Wooden Base Accents",
      washCare: "Wipe with damp cloth or gentle rinse",
      craftTime: "1 to 2 days",
      durability: "Sturdy structured corners",
      baseMaterial: "Anti-slip felt backing",
      reusable: true,
    },
    sizes: [
      { id: "s-corners-std", label: "Standard Set (6\" x 6\" each)", dimensions: "Set of 4 pieces (6\"x6\")", priceMultiplier: 1.0, isPopular: true },
      { id: "s-corners-lrg", label: "Grand Door Set (9\" x 9\" each)", dimensions: "Set of 4 pieces (9\"x9\")", priceMultiplier: 1.45 },
    ],
    colorThemes: [
      { id: "c-shubh-marigold", name: "Marigold Yellow & Red", colors: ["#EAB308", "#DC2626"], previewTag: "Auspicious" },
      { id: "c-shubh-pink", name: "Rani Pink & Gold", colors: ["#DB2777", "#F59E0B"] },
    ],
    rating: 4.7,
    reviewsCount: 31,
  },
  {
    id: "prod-7",
    title: "Handcrafted Woolen Traditional Door Toran with Bells",
    slug: "handcrafted-woolen-traditional-door-toran",
    subtitle: "Auspicious doorway hanging woven with circular flowers, kalash & ghungroos",
    description: "Welcome guests and positive energy into your abode. Woven with alternating flower pendants, handcrafted woolen beads, and gentle brass bells.",
    detailedDescription: "Fits all standard Indian doorways (3 feet to 3.5 feet). Soft, unbreakable, and folds neatly into a small box when not in use.",
    category: "entrance-torans",
    price: 849,
    compareAtPrice: 1199,
    inStock: true,
    stockCount: 11,
    isBestseller: false,
    isNewArrival: true,
    isCustomizable: true,
    featuredMotif: "Toran",
    motifs: ["Toran", "Circular Flowers", "Kalash"],
    images: [
      "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=900",
    ],
    features: [
      "38-inch length tailored for standard main doors",
      "Equipped with sturdy brass hanging loops on both ends",
      "Washable threads that do not bleed or shrink",
    ],
    specifications: {
      material: "4-ply Acrylic Yarn & Brass Ghungroos",
      washCare: "Gentle dip in soapy water, air dry",
      craftTime: "2 days",
      durability: "Reinforced woven cord",
      baseMaterial: "Braided wool base",
      reusable: true,
    },
    sizes: [
      { id: "s-toran-3ft", label: "Standard Door (3.2 Feet / 38\")", dimensions: "38 inches long", priceMultiplier: 1.0, isPopular: true },
      { id: "s-toran-4ft", label: "Wide Main Gate (4.2 Feet / 50\")", dimensions: "50 inches long", priceMultiplier: 1.35 },
    ],
    colorThemes: [
      { id: "c-toran-festive", name: "Haldi Yellow, Green & Maroon", colors: ["#EAB308", "#16A34A", "#991B1B"], previewTag: "Traditional" },
      { id: "c-toran-rani", name: "Rani Pink & Golden Ochre", colors: ["#DB2777", "#D97706"] },
    ],
    rating: 4.9,
    reviewsCount: 19,
  },
  {
    id: "prod-8",
    title: "Pooja Thali & Brass Diya Velvet-Woolen Mat Duo",
    slug: "pooja-thali-brass-diya-mat-duo",
    subtitle: "Protective washable mats with auspicious lotus trims (Pack of 2)",
    description: "Keep your wooden and marble mandirs spotless from kumkum, oil, and prasad stains. Woven with protective thermal felt and charming floral borders.",
    detailedDescription: "Includes 1 larger 11-inch Thali base mat and 1 matching 7-inch Aarti/Diya coaster. Fully washable and dry within hours.",
    category: "pooja-thali-mats",
    price: 499,
    compareAtPrice: 699,
    inStock: true,
    stockCount: 25,
    isBestseller: true,
    isNewArrival: false,
    isCustomizable: true,
    featuredMotif: "Diya",
    motifs: ["Diya", "Lotus", "Om"],
    images: [
      "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=900",
    ],
    features: [
      "Pack of 2 matching mandir mats (Thali Mat + Diya Mat)",
      "Protects mandir marble and wood from oil & haldi-kumkum marks",
      "Stain-resistant and easily washable",
    ],
    specifications: {
      material: "Oil-resistant Felt & Acrylic Wool Trims",
      washCare: "Quick tap rinse with detergent",
      craftTime: "1 day",
      durability: "High endurance daily use",
      baseMaterial: "Non-absorbent felt core",
      reusable: true,
    },
    sizes: [
      { id: "s-thali-duo", label: "Standard Duo (11\" + 7\")", dimensions: "Pack of 2 mats", priceMultiplier: 1.0, isPopular: true },
      { id: "s-thali-trio", label: "Grand Mandir Trio (14\" + 9\" + 6\")", dimensions: "Pack of 3 mats", priceMultiplier: 1.45 },
    ],
    colorThemes: [
      { id: "c-thali-kumkum", name: "Kumkum Red & Sun Gold", colors: ["#DC2626", "#F59E0B"], previewTag: "Pooja Special" },
      { id: "c-thali-yellow", name: "Haldi Ochre & Deep Pink", colors: ["#D97706", "#DB2777"] },
    ],
    rating: 5.0,
    reviewsCount: 41,
  },
  {
    id: "prod-9",
    title: "The Griha Pravesh & Housewarming Auspicious Gift Hamper",
    slug: "griha-pravesh-housewarming-auspicious-hamper",
    subtitle: "Complete handcrafted home decor set packed in an artisan gift box",
    description: "The ultimate handcrafted blessing for new homes and weddings. Contains 1 Grand Kalash Woolen Rangoli (18\"), 1 Shubh-Labh Doorway Corner Set (4 pcs), and 2 Diya Coasters with a personalized handwritten card.",
    detailedDescription: "Presented in a luxury reusable kraft gift box tied with handmade woolen pom-pom strings and a custom personalized congratulatory card from Aarya.",
    category: "festive-hampers",
    price: 1899,
    compareAtPrice: 2599,
    inStock: true,
    stockCount: 6,
    isBestseller: true,
    isNewArrival: true,
    isCustomizable: true,
    featuredMotif: "Kalash",
    motifs: ["Kalash", "Shubh-Labh", "Diya", "Circular Flowers"],
    images: [
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1605651202774-7d573fd3f12d?auto=format&fit=crop&q=80&w=900",
      "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&q=80&w=900",
    ],
    features: [
      "1x Grand Kalash Woolen Rangoli Mat (18\" Diameter)",
      "1x Set of 4 Shubh-Labh Woolen Corner Accents",
      "2x Handcrafted Diya Coasters",
      "Luxury gift packaging with personalized name & blessing card",
    ],
    specifications: {
      material: "Assorted Premium Acrylic Wool & Velvet Accents",
      washCare: "Hand wash individual items gently",
      craftTime: "3 to 4 days artisan creation",
      durability: "All items reusable year after year",
      baseMaterial: "Anti-slip felt on all mats",
      reusable: true,
    },
    sizes: [
      { id: "s-hamper-standard", label: "Standard Hamper Box (4 Products)", dimensions: "12\" x 12\" x 4\" Box", priceMultiplier: 1.0, isPopular: true },
      { id: "s-hamper-luxury", label: "Royal Grand Hamper (6 Products + Toran)", dimensions: "16\" x 16\" x 5\" Box", priceMultiplier: 1.5 },
    ],
    colorThemes: [
      { id: "c-hamper-traditional", name: "Auspicious Haldi, Kumkum & Gold", colors: ["#F59E0B", "#DC2626", "#BE185D"], previewTag: "Hamper Special" },
      { id: "c-hamper-peacock", name: "Royal Peacock Blue & Emerald", colors: ["#1E40AF", "#047857", "#D97706"] },
    ],
    rating: 5.0,
    reviewsCount: 18,
  },
];

export const INITIAL_PROMOS: PromoCode[] = [
  {
    code: "WELCOMEAARYA",
    discountType: "percentage",
    discountValue: 10,
    minOrderValue: 499,
    description: "10% OFF on your first handcrafted order",
    active: true,
  },
  {
    code: "FESTIVE100",
    discountType: "fixed",
    discountValue: 100,
    minOrderValue: 999,
    description: "Flat ₹100 OFF on orders above ₹999",
    active: true,
  },
  {
    code: "AARYAHOME",
    discountType: "percentage",
    discountValue: 15,
    minOrderValue: 1499,
    description: "15% OFF on Grand Rangolis and Hampers",
    active: true,
  },
];

export const INITIAL_BANNER: AnnouncementBanner = {
  id: "banner-1",
  enabled: true,
  badge: "✨ 100% Handcrafted",
  text: "Personalized Woolen Mat Rangolis & Home Decor • Use Code",
  highlightText: "WELCOMEAARYA for 10% OFF",
  backgroundColor: "from-amber-600 via-rose-600 to-amber-700",
  textColor: "text-white",
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: "AL-78219",
    customer: {
      fullName: "Pooja Deshmukh",
      phoneNumber: "+91 98201 45892",
      addressLine1: "Flat 402, Mayur Heights, Near Ganesh Mandir",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411005",
      orderNotes: "Please make the Kalash with extra deep red and haldi yellow wool!",
      otp: ""
    },
    items: [
      {
        id: "item-1",
        product: INITIAL_PRODUCTS[0],
        quantity: 1,
        unitPrice: 899,
        customization: {
          selectedSize: INITIAL_PRODUCTS[0].sizes[1],
          selectedColorTheme: INITIAL_PRODUCTS[0].colorThemes[0],
          customNameText: "Deshmukh Family",
          chosenMotif: "Kalash",
          customNotes: "Custom text for entrance display",
        },
      },
    ],
    subtotal: 899,
    discount: 89,
    appliedPromo: "WELCOMEAARYA",
    giftWrapping: true,
    giftWrappingFee: 49,
    shippingFee: 0,
    totalAmount: 859,
    status: "Weaving & Handcrafting 🧶",
    paymentMethod: "Direct Booking / COD",
    paymentStatus: "Confirmed",
    createdAt: "2026-08-30T11:20:00.000Z",
    estimatedDeliveryDate: "2026-09-05",
    artisanNote: "Yarn selected. Base felt cut. Weaving in progress.",
  },
  {
    id: "AL-78224",
    customer: {
      fullName: "Ananya Iyer",
      phoneNumber: "+91 94452 78120",
      addressLine1: "Villa 12, Palm Meadows, Whitefield",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560066",
      orderNotes: "Need by this weekend for Varalakshmi pooja if possible.",
      otp: ""
    },
    items: [
      {
        id: "item-2",
        product: INITIAL_PRODUCTS[2],
        quantity: 1,
        unitPrice: 799,
        customization: {
          selectedSize: INITIAL_PRODUCTS[2].sizes[1],
          selectedColorTheme: INITIAL_PRODUCTS[2].colorThemes[0],
          chosenMotif: "Laxmi Charan",
        },
      },
      {
        id: "item-3",
        product: INITIAL_PRODUCTS[7],
        quantity: 1,
        unitPrice: 499,
        customization: {
          selectedSize: INITIAL_PRODUCTS[7].sizes[0],
          selectedColorTheme: INITIAL_PRODUCTS[7].colorThemes[0],
          chosenMotif: "Diya",
        },
      },
    ],
    subtotal: 1298,
    discount: 100,
    appliedPromo: "FESTIVE100",
    giftWrapping: false,
    giftWrappingFee: 0,
    shippingFee: 0,
    totalAmount: 1198,
    status: "Quality Checked & Packed 🎁",
    paymentMethod: "Direct Booking / COD",
    paymentStatus: "Confirmed",
    createdAt: "2026-08-31T09:45:00.000Z",
    estimatedDeliveryDate: "2026-09-04",
    artisanNote: "Finished and packaged. Ready for courier pickup.",
  },
];
